import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, Package, RefreshCw, ShoppingBag, TrendingUp, AlertTriangle, Shirt } from 'lucide-react'

const API = import.meta.env.VITE_API_URL || 'http://localhost:3001'
const money = (cents: number) => `$${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2 })}`
type Product = { _id: string; name: string; imageUrl: string; availableStock: number; totalStock: number; priceCents: number }
type Order = { _id: string; status: string; quantity: number; amountCents: number; updatedAt: string; stripePaymentIntentId: string; productId: { name: string } | null }
type Overview = { products: Product[]; metrics: { totalProducts: number; availableUnits: number; outOfStock: number; pendingReservations: number; revenueCents: number; orders: Record<string, number> } }

export default function Admin() {
  const [key, setKey] = useState(sessionStorage.getItem('atelier-admin-key') || '')
  const [overview, setOverview] = useState<Overview | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState<string | null>(null)
  const headers = useCallback(() => key ? { 'x-admin-key': key } : {}, [key])
  const load = useCallback(async () => { try { const [overviewRes, ordersRes] = await Promise.all([fetch(`${API}/api/admin/overview`, { headers: headers() }), fetch(`${API}/api/admin/orders`, { headers: headers() })]); if (!overviewRes.ok) throw new Error(overviewRes.status === 401 ? 'Enter your staff API key to access operations.' : 'Could not load the operations dashboard.'); const [overviewData, ordersData] = await Promise.all([overviewRes.json(), ordersRes.json()]); setOverview(overviewData); setOrders(ordersData.orders); setError('') } catch (err) { setError(err instanceof Error ? err.message : 'Could not load dashboard.') } }, [headers])
  useEffect(() => {
    load()
    const refresh = window.setInterval(load, 4000)
    return () => window.clearInterval(refresh)
  }, [load])
  const saveStock = async (productId: string, availableStock: number) => { setSaving(productId); try { const response = await fetch(`${API}/api/admin/products/${productId}/stock`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', ...headers() }, body: JSON.stringify({ availableStock }) }); if (!response.ok) throw new Error((await response.json()).error); await load() } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save stock.') } finally { setSaving(null) } }
  const submitKey = (event: React.FormEvent) => { event.preventDefault(); sessionStorage.setItem('atelier-admin-key', key); load() }
  if (error && !overview) return <main className="admin-login"><a href="/" className="back"><ArrowLeft size={16}/> Storefront</a><div className="admin-login-card"><p className="eyebrow">ATELIER / OPERATIONS</p><h1>Store control room.</h1><p>{error}</p><form onSubmit={submitKey}><input value={key} onChange={(e) => setKey(e.target.value)} type="password" placeholder="Staff API key" /><button className="pay-button">Enter dashboard</button></form><small>For local demos, leave this empty unless <code>ADMIN_API_KEY</code> is set in the server environment.</small></div></main>
  if (!overview) return <div className="admin-loading">Loading operations…</div>
  const { metrics, products } = overview
  return <main className="admin-shell"><header className="admin-header"><a href="/" className="brand"><Shirt className="brand-icon" size={20} strokeWidth={1.7}/>ATELIER<span>TEE</span></a><div><span className="live-dot"/> LIVE OPERATIONS <button onClick={load} className="icon-button" aria-label="Refresh"><RefreshCw size={16}/></button></div></header><div className="admin-content"><div className="admin-title"><div><p className="eyebrow">STORE MANAGEMENT</p><h1>Overview</h1></div><p>Inventory and payment state update from the same reservation records used by checkout.</p></div>{error && <div className="notice"><span>{error}</span></div>}
    <section className="metric-grid"><Metric icon={<Package/>} label="Sellable units" value={metrics.availableUnits}/><Metric icon={<AlertTriangle/>} label="Sold out SKUs" value={metrics.outOfStock}/><Metric icon={<ShoppingBag/>} label="Pending holds" value={metrics.pendingReservations}/><Metric icon={<TrendingUp/>} label="Paid revenue" value={money(metrics.revenueCents)}/></section>
    <section className="admin-section"><div className="section-bar"><div><h2>Inventory</h2><p>{metrics.totalProducts} catalog SKUs · inventory capped at five for testing</p></div></div><div className="inventory-table"><div className="table-head"><span>Product</span><span>Price</span><span>Original</span><span>Available now</span></div>{products.map((product) => <div className="inventory-row" key={product._id}><div className="admin-product"><img src={product.imageUrl} alt=""/><span>{product.name}</span></div><span>{money(product.priceCents)}</span><span>{product.totalStock}</span><label className="stock-control"><input type="number" min="0" max="5" defaultValue={product.availableStock} key={`${product._id}-${product.availableStock}`} onBlur={(e) => { const value = Number(e.target.value); if (value !== product.availableStock) saveStock(product._id, value) }} /><span>{saving === product._id ? 'Saving' : 'save on blur'}</span></label></div>)}</div></section>
    <section className="admin-section"><div className="section-bar"><div><h2>Recent payments</h2><p>{metrics.orders.succeeded || 0} succeeded · {metrics.orders.failed || 0} failed · {metrics.orders.pending || 0} pending</p></div></div><div className="orders-table"><div className="order-head"><span>Order</span><span>Status</span><span>Amount</span><span>Updated</span></div>{orders.length ? orders.map((order) => <div className="order-row" key={order._id}><div><strong>{order.productId?.name || 'Archived product'}</strong><small>{order.stripePaymentIntentId}</small></div><span className={`status ${order.status}`}>{order.status}</span><strong>{money(order.amountCents)}</strong><span>{new Date(order.updatedAt).toLocaleString()}</span></div>) : <p className="empty-orders">No payment attempts yet. Checkout activity will appear here.</p>}</div></section></div></main>
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <div className="metric"><span>{icon}</span><p>{label}</p><strong>{value}</strong></div> }
